mysql_master:
  image: mysql:5.7
  restart:
  - always
  ports:
  - 3307:3306
  volumes:
  - ./volumes/mysql_master:/var/lib/mysql
  - './volumes/mysql_cnf_master:/etc/mysql/conf.d:ro'
  environment:
     MYSQL_ROOT_PASSWORD: Hello.123
